apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homework-chart.fullname" . }}
data:
  LOGGING_OUTPUT: {{.Values.logging.output | quote}}
  LOGGING_FORMAT: {{.Values.logging.format | quote}}
  LOGGING_LEVEL: {{.Values.logging.level | quote}}
  HTTP_PORT: {{.Values.service.port | quote}}
  DB_PORT: {{.Values.mongodb.service.port | quote}}
  DB_HOST: "mywork-mongodb"
  DB_DATABASE: {{.Values.mongodb.mongodbDatabase | quote}}
---
apiVersion: v1
kind: Secret
metadata:
  name: homework-secret
type: Opaque
data:
  DB_LOGIN: {{.Values.mongodb.mongodbUsername | b64enc | quote}}
  DB_PASSWORD: {{.Values.mongodb.mongodbPassword | b64enc | quote}}